### ISSUE TITLE
Error in console with mysql connection

### ISSUE THREAD

**Issue by UnitedCraft** [Tallcraft/NerfPhantoms#16]
Server version: purpur-1.17.1-1427
Plugin version: NerfPhantoms-1.3.0

Config:
`enabledWorlds:
- world
- world_nether
- world_the_end
allowNaturalSpawn: true
onlyNerfNatural: true
muteSound: false
disableAI: false
health: 20.0
damageModifier: 1.0
fixedSize:
  enabled: false
  value: 1
database:
  enabled: true
  type: mysql
  host: myip
  port: 3306
  name: xxx
  username: xxx
  password: xxx`
`

[14:09:01 INFO]: [NerfPhantoms] Error while fetching player data from storage
[14:09:01 WARN]: java.sql.SQLNonTransientConnectionException: No operations allowed after connection closed.
[14:09:01 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110)
[14:09:01 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
[14:09:01 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
[14:09:01 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63)
[14:09:01 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73)
[14:09:01 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:73)
[14:09:01 WARN]:        at com.mysql.cj.jdbc.ConnectionImpl.prepareStatement(ConnectionImpl.java:1664)
[14:09:01 WARN]:        at com.mysql.cj.jdbc.ConnectionImpl.prepareStatement(ConnectionImpl.java:1580)
[14:09:01 WARN]:        at NerfPhantoms-1.3.0.jar//com.tallcraft.nerfphantoms.Storage.getPhantomDisabled(Storage.java:43)
[14:09:01 WARN]:        at NerfPhantoms-1.3.0.jar//com.tallcraft.nerfphantoms.NerfPhantoms$3.run(NerfPhantoms.java:245)
[14:09:01 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101)
[14:09:01 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[14:09:01 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[14:09:01 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[14:09:01 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[14:09:01 WARN]:        at java.base/java.lang.Thread.run(Unknown Source)
[14:09:01 WARN]: Caused by: com.mysql.cj.exceptions.ConnectionIsClosedException: No operations allowed after connection closed.
[14:09:01 WARN]:        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[14:09:01 WARN]:        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[14:09:01 WARN]:        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[14:09:01 WARN]:        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source)
[14:09:01 WARN]:        at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
[14:09:01 WARN]:        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
[14:09:01 WARN]:        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
[14:09:01 WARN]:        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151)
[14:09:01 WARN]:        at com.mysql.cj.NativeSession.checkClosed(NativeSession.java:1171)
[14:09:01 WARN]:        at com.mysql.cj.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:573)
[14:09:01 WARN]:        at com.mysql.cj.jdbc.ConnectionImpl.prepareStatement(ConnectionImpl.java:1595)
[14:09:01 WARN]:        ... 9 more
[14:09:01 WARN]: Caused by: com.mysql.cj.exceptions.CJCommunicationsException: The last packet successfully received from the server was 36,293,446 milliseconds ago. The last packet sent successfully to the server was 36,293,446 milliseconds ago. is longer than the server configured value of 'wait_timeout'. You should consider either expiring and/or testing connection validity before use in your application, increasing the server configured values for client timeouts, or using the Connector/J connection property 'autoReconnect=true' to avoid this problem.
[14:09:01 WARN]:        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[14:09:01 WARN]:        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[14:09:01 WARN]:        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[14:09:01 WARN]:        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source)
[14:09:01 WARN]:        at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
[14:09:01 WARN]:        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
[14:09:01 WARN]:        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
[14:09:01 WARN]:        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151)
[14:09:01 WARN]:        at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:167)
[14:09:01 WARN]:        at com.mysql.cj.protocol.a.NativeProtocol.send(NativeProtocol.java:577)
[14:09:01 WARN]:        at com.mysql.cj.protocol.a.NativeProtocol.sendCommand(NativeProtocol.java:632)
[14:09:01 WARN]:        at com.mysql.cj.protocol.a.NativeProtocol.sendQueryPacket(NativeProtocol.java:948)
[14:09:01 WARN]:        at com.mysql.cj.NativeSession.execSQL(NativeSession.java:1075)
[14:09:01 WARN]:        at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:930)
[14:09:01 WARN]:        at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:1003)
[14:09:01 WARN]:        at NerfPhantoms-1.3.0.jar//com.tallcraft.nerfphantoms.Storage.getPhantomDisabled(Storage.java:45)
[14:09:01 WARN]:        ... 7 more
[14:09:01 WARN]: Caused by: java.net.SocketException: Connection reset by peer
[14:09:01 WARN]:        at java.base/sun.nio.ch.NioSocketImpl.implWrite(Unknown Source)
[14:09:01 WARN]:        at java.base/sun.nio.ch.NioSocketImpl.write(Unknown Source)
[14:09:01 WARN]:        at java.base/sun.nio.ch.NioSocketImpl$2.write(Unknown Source)
[14:09:01 WARN]:        at java.base/java.net.Socket$SocketOutputStream.write(Unknown Source)
[14:09:01 WARN]:        at java.base/java.io.BufferedOutputStream.flushBuffer(Unknown Source)
[14:09:01 WARN]:        at java.base/java.io.BufferedOutputStream.flush(Unknown Source)
[14:09:01 WARN]:        at com.mysql.cj.protocol.a.SimplePacketSender.send(SimplePacketSender.java:55)
[14:09:01 WARN]:        at com.mysql.cj.protocol.a.TimeTrackingPacketSender.send(TimeTrackingPacketSender.java:50)
[14:09:01 WARN]:        at com.mysql.cj.protocol.a.NativeProtocol.send(NativeProtocol.java:568)
[14:09:01 WARN]:        ... 13 more`

**After adding a possibility to disable spawn phantoms**

[14:21:36 INFO]: RavenskyPaul issued server command: /nerfphantoms togglespawn RavenskyPaul
[14:21:36 INFO]: [NerfPhantoms] Error while updating player data in storage
[14:21:36 WARN]: java.sql.SQLNonTransientConnectionException: No operations allowed after connection closed.
[14:21:36 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110)
[14:21:36 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
[14:21:36 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
[14:21:36 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63)
[14:21:36 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73)
[14:21:36 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:73)
[14:21:36 WARN]:        at com.mysql.cj.jdbc.ConnectionImpl.prepareStatement(ConnectionImpl.java:1664)
[14:21:36 WARN]:        at com.mysql.cj.jdbc.ConnectionImpl.prepareStatement(ConnectionImpl.java:1580)
[14:21:36 WARN]:        at NerfPhantoms-1.3.0.jar//com.tallcraft.nerfphantoms.Storage.setPhantomDisabled(Storage.java:57)
[14:21:36 WARN]:        at NerfPhantoms-1.3.0.jar//com.tallcraft.nerfphantoms.NerfPhantoms$2.run(NerfPhantoms.java:165)
[14:21:36 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101)
[14:21:36 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[14:21:36 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[14:21:36 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[14:21:36 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[14:21:36 WARN]:        at java.base/java.lang.Thread.run(Unknown Source)
[14:21:36 WARN]: Caused by: com.mysql.cj.exceptions.ConnectionIsClosedException: No operations allowed after connection closed.
[14:21:36 WARN]:        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[14:21:36 WARN]:        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[14:21:36 WARN]:        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[14:21:36 WARN]:        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source)
[14:21:36 WARN]:        at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
[14:21:36 WARN]:        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
[14:21:36 WARN]:        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
[14:21:36 WARN]:        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151)
[14:21:36 WARN]:        at com.mysql.cj.NativeSession.checkClosed(NativeSession.java:1171)
[14:21:36 WARN]:        at com.mysql.cj.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:573)
[14:21:36 WARN]:        at com.mysql.cj.jdbc.ConnectionImpl.prepareStatement(ConnectionImpl.java:1595)
[14:21:36 WARN]:        ... 9 more
[14:21:36 WARN]: Caused by: com.mysql.cj.exceptions.CJCommunicationsException: The last packet successfully received from the server was 36,293,446 milliseconds ago. The last packet sent successfully to the server was 36,293,446 milliseconds ago. is longer than the server configured value of 'wait_timeout'. You should consider either expiring and/or testing connection validity before use in your application, increasing the server configured values for client timeouts, or using the Connector/J connection property 'autoReconnect=true' to avoid this problem.
[14:21:36 WARN]:        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[14:21:36 WARN]:        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[14:21:36 WARN]:        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[14:21:36 WARN]:        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source)
[14:21:36 WARN]:        at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
[14:21:36 WARN]:        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
[14:21:36 WARN]:        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
[14:21:36 WARN]:        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151)
[14:21:36 WARN]:        at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:167)
[14:21:36 WARN]:        at com.mysql.cj.protocol.a.NativeProtocol.send(NativeProtocol.java:577)
[14:21:36 WARN]:        at com.mysql.cj.protocol.a.NativeProtocol.sendCommand(NativeProtocol.java:632)
[14:21:36 WARN]:        at com.mysql.cj.protocol.a.NativeProtocol.sendQueryPacket(NativeProtocol.java:948)
[14:21:36 WARN]:        at com.mysql.cj.NativeSession.execSQL(NativeSession.java:1075)
[14:21:36 WARN]:        at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:930)
[14:21:36 WARN]:        at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:1003)
[14:21:36 WARN]:        at NerfPhantoms-1.3.0.jar//com.tallcraft.nerfphantoms.Storage.getPhantomDisabled(Storage.java:45)
[14:21:36 WARN]:        at NerfPhantoms-1.3.0.jar//com.tallcraft.nerfphantoms.NerfPhantoms$3.run(NerfPhantoms.java:245)
[14:21:36 WARN]:        ... 6 more
[14:21:36 WARN]: Caused by: java.net.SocketException: Connection reset by peer
[14:21:36 WARN]:        at java.base/sun.nio.ch.NioSocketImpl.implWrite(Unknown Source)
[14:21:36 WARN]:        at java.base/sun.nio.ch.NioSocketImpl.write(Unknown Source)
[14:21:36 WARN]:        at java.base/sun.nio.ch.NioSocketImpl$2.write(Unknown Source)
[14:21:36 WARN]:        at java.base/java.net.Socket$SocketOutputStream.write(Unknown Source)
[14:21:36 WARN]:        at java.base/java.io.BufferedOutputStream.flushBuffer(Unknown Source)
[14:21:36 WARN]:        at java.base/java.io.BufferedOutputStream.flush(Unknown Source)
[14:21:36 WARN]:        at com.mysql.cj.protocol.a.SimplePacketSender.send(SimplePacketSender.java:55)
[14:21:36 WARN]:        at com.mysql.cj.protocol.a.TimeTrackingPacketSender.send(TimeTrackingPacketSender.java:50)
[14:21:36 WARN]:        at com.mysql.cj.protocol.a.NativeProtocol.send(NativeProtocol.java:568)
[14:21:36 WARN]:        ... 13 more

**Comment by Trikolon** [comment]
There could be an issue with your MySQL server. Looks like a connection loss. Do any other plugins use the same server and do they have issues?

**Comment by Trikolon** [comment]
No reply from reporter, closing.
